export const chocolates = [
    {
        occurences: 3,
        chocolat_id: 1,
        nom: "Tablette Noir 70%",
        description: "Delicieuse tablette de chocolat noir avec 70% de cacao.",
        categorie: "Tablettes de chocolat",
        origine: "Côte d'Ivoire",
        prix: "38400.00",
        image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fzerodechet-tours.fr%2Fbiscuits-chocolats%2F54-tablette-chocolat-noir-amandes.html&psig=AOvVaw39mOtuMjacJ2fGEssc2AIf&ust=1714248354039000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCIj3qvTW4IUDFQAAAAAdAAAAABAE",
        categorie_id: 1,
        origine_id: 1
    },
    {
        occurences: 2,
        chocolat_id: 8,
        nom: "Tablette Noir Intense",
        description: "Tablette de chocolat noir avec 85% de cacao pour une experience intense.",
        categorie: "Tablettes de chocolat",
        origine: "Côte d'Ivoire",
        prix: "39500.00",
        image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.femmeactuelle.fr%2Fcuisine%2Ftendance-cuisine%2Fle-meilleur-des-tablettes-a-patisser-00028&psig=AOvVaw0gLd8bbqiGNLx23wwmnTWY&ust=1714248468750000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCMDRw6rX4IUDFQAAAAAdAAAAABAR",
        categorie_id: 1,
        origine_id: 1
    },
    {
        occurences: 1,
        chocolat_id: 14,
        nom: "Tablette Lait Caramel Beurre Sale",
        description: "Tablette de chocolat au lait avec un caramel au beurre sale fondant.",
        categorie: "Tablettes de chocolat",
        origine: "Côte d'Ivoire",
        prix: "43500.00",
        image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.stephanepasco.com%2Fproduit%2Ftablette-gourmande-caramel-praline-chocolat-lait%2F&psig=AOvVaw1K0Wie2nvvF_7E3rQVSuyN&ust=1714248557160000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCPij2dTX4IUDFQAAAAAdAAAAABAK",
        categorie_id: 1,
        origine_id: 1
    },
    {
        occurences: 5,
        chocolat_id: 9,
        nom: "Praline Noisette",
        description: "Praline fondant aux eclats de noisettes torrefiees.",
        categorie: "Pralinés",
        origine: "Venezuela",
        prix: "44000.00",
        image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.emotionssucrees.fr%2Fproduit%2Ftablette-chocolat-noir-praline-noisette%2F&psig=AOvVaw0t_piC8xy73Wzhm4LFlc8O&ust=1714246002902000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCIDJypPO4IUDFQAAAAAdAAAAABAE",
        categorie_id: 2,
        origine_id: 2
    },
    {
        chocolat_id: 15,
        nom: "Praline Amande Grillee",
        description: "Praline croquant avec des eclats d amandes grillees.",
        categorie: "Pralinés",
        origine: "Venezuela",
        prix: "47000.00",
        image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fchocolats-frigoulette.fr%2Fproduit%2Ftablette-amandes-grillees%2F&psig=AOvVaw2HbYN2XuyCCF8LhdP75IXS&ust=1714246074558000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCLCamLXO4IUDFQAAAAAdAAAAABAn",
        categorie_id: 2,
        origine_id: 2
    },
    {
        chocolat_id: 2,
        nom: "Tablette Lait aux Noisettes",
        description: "Tablette de chocolat au lait avec des eclats de noisettes croquants.",
        categorie: "Tablettes de chocolat",
        origine: "Venezuela",
        prix: "24000.00",
        image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.secretdecacao.com%2Fproduit%2Flait-tablette-aux-noisettes%2F&psig=AOvVaw0U_N2zo-2fWiAbn35zdzGq&ust=1714246244519000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCOjekIbP4IUDFQAAAAAdAAAAABAJ",
        categorie_id: 1,
        origine_id: 2
    },
    {
        chocolat_id: 10,
        nom: "Truffe Chocolat Noir",
        description: "Truffe au chocolat noir riche et onctueuse.",
        categorie: "Truffes",
        origine: "Equateur",
        prix: "35500.00",
        image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.cuisineaz.com%2Frecettes%2Ftruffes-au-chocolat-5675.aspx&psig=AOvVaw1ZPpfTPrzVYiSczdmOGVeG&ust=1714246337992000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCKCY0rLP4IUDFQAAAAAdAAAAABAE",
        categorie_id: 3,
        origine_id: 3
    },
    {
        chocolat_id: 16,
        nom: "Truffe Chocolat au Lait",
        description: "Truffe au chocolat au lait onctueux et fondant.",
        categorie: "Truffes",
        origine: "Equateur",
        prix: "28900.00",
        image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.academiedugout.fr%2Frecettes%2Ftruffes-au-chocolat_9973_2&psig=AOvVaw0stokgyvP9uN-XVaIBWD2r&ust=1714246390925000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCID028vP4IUDFQAAAAAdAAAAABAR",
        categorie_id: 3,
        origine_id: 3
    },
    {
        chocolat_id: 3,
        nom: "Praline Fondant",
        description: "Praline fondant enrobe de chocolat noir.",
        categorie: "Pralinés",
        origine: "Equateur",
        prix: "43200.00",
        image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fpartagestesrecettes.fr%2Ffondant-praline-healthy&psig=AOvVaw3n_BlHurbXfi0cVNEdrnMk&ust=1714246664903000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCKjnu87Q4IUDFQAAAAAdAAAAABAJ",
        categorie_id: 2,
        origine_id: 3
    },
    {
        chocolat_id: 11,
        nom: "Chocolat Chaud Classique",
        description: "Chocolat chaud traditionnel … base de cacao pur.",
        categorie: "Chocolats chauds",
        origine: "Madagascar",
        prix: "19200.00",
        image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fsosoir.lesoir.be%2Fles-ingredients-privilegier-pour-un-chocolat-chaud-moins-calorique&psig=AOvVaw3xPIw8M4Tsyp9W_02g1Tv6&ust=1714248644391000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCOi2jv7X4IUDFQAAAAAdAAAAABAQ",
        categorie_id: 4,
        origine_id: 4
    },
    {
        chocolat_id: 17,
        nom: "Chocolat Chaud Cannelle Vanille",
        description: "Chocolat chaud aromatise … la cannelle et … la vanille pour une touche exotique.",
        categorie: "Chocolats chauds",
        origine: "Madagascar",
        prix: "18000.00",
        image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.ptitecuisinedepauline.com%2F2020%2F02%2Fchocolat-blanc-chaud.html&psig=AOvVaw1dNt9ZJzwuDmofjDxRr5hE&ust=1714246839609000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCJiq4KHR4IUDFQAAAAAdAAAAABA0",
        categorie_id: 4,
        origine_id: 4
    },
    {
        chocolat_id: 4,
        nom: "Truffe Chocolat Blanc",
        description: "Truffe au chocolat blanc avec une touche de vanille.",
        categorie: "Truffes",
        origine: "Madagascar",
        prix: "40000.00",
        image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fgourmand.viepratique.fr%2Frecettes-par-ingredient%2Fsucre%2Ftruffes-chocolat-blanc-et-noix-de-coco-25655.html&psig=AOvVaw0OXL6maW1Lkg7EInwMhCCT&ust=1714246998209000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCOigq-3R4IUDFQAAAAAdAAAAABAE",
        categorie_id: 3,
        origine_id: 4
    },
    {
        chocolat_id: 12,
        nom: "Dragees au Chocolat Blanc",
        description: "Dragees aux amandes enrobees de chocolat blanc.",
        categorie: "Dragées",
        origine: "Pérou",
        prix: "24200.00",
        image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.badaboum.fr%2F1-kilo-de-dragees-blanc-au-chocolat.html&psig=AOvVaw3FzDhl_H9h0hvhSo4Agxxc&ust=1714247100204000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCNDPiJ7S4IUDFQAAAAAdAAAAABAE",
        categorie_id: 5,
        origine_id: 5
    },
    {
        chocolat_id: 18,
        nom: "Dragees aux Noix de Pecan",
        description: "Dragees aux noix de pecan enrobees de chocolat au lait.",
        categorie: "Dragées",
        origine: "Pérou",
        prix: "18500.00",
        image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.fustuq-hail.com%2Ffr%2Fshop%2Fchocolate%2Fdragee-caramel-chocolate%2F&psig=AOvVaw3Xl5fILzcDs3thKIPOqvwi&ust=1714247147494000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCPDTzLTS4IUDFQAAAAAdAAAAABAE",
        categorie_id: 5,
        origine_id: 5
    },
    {
        chocolat_id: 5,
        nom: "Chocolat Chaud epice",
        description: "Melange de cacao avec une touche de cannelle et de piment.",
        categorie: "Chocolats chauds",
        origine: "Pérou",
        prix: "28000.00",
        image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.mesrecettesfaciles.fr%2Frecipe%2Fchocolat-chaud-aux-epices-d-automne&psig=AOvVaw2Jc7ct_5bMJ5zKTdkyCwJ3&ust=1714247225530000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCKjE59nS4IUDFQAAAAAdAAAAABAj",
        categorie_id: 4,
        origine_id: 5
    },
    {
        chocolat_id: 13,
        nom: "Barre Chocolat Noisette",
        description: "Barre de chocolat noir aux eclats de noisettes croustillants.",
        categorie: "Barres de chocolat",
        origine: "Mexique",
        prix: "31000.00",
        image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.puyricard.fr%2Ffr%2Fchocolats%2F1958-barre-choco-noisettes-caramel.html&psig=AOvVaw3xkvIITYQTemVWsydCKwo3&ust=1714247600114000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCNjPuYzU4IUDFQAAAAAdAAAAABAL",
        categorie_id: 6,
        origine_id: 6
    },
    {
        chocolat_id: 19,
        nom: "Barre Chocolat au Nougat",
        description: "Barre de chocolat noir avec des morceaux de nougat tendre.",
        categorie: "Barres de chocolat",
        origine: "Mexique",
        prix: "36000.00",
        image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Flacabanesurleroc.ca%2Fproducts%2Fbarre-nougat-ganache-au-miel-et-chocolat-noir&psig=AOvVaw3oKROG_dJrPWoRvv-GQ-EK&ust=1714248071289000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCKDQ_-zV4IUDFQAAAAAdAAAAABAK",
        categorie_id: 6,
        origine_id: 6
    },
    {
        chocolat_id: 6,
        nom: "Dragees aux Amandes",
        description: "Dragees aux amandes enrobees de chocolat au lait.",
        categorie: "Dragées",
        origine: "Mexique",
        prix: "32000.00",
        image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.fleursdedragees.com%2Fdragees-amande%2F2057-1kg-dragees-amande-pas-cher-blanche-3322219051015.html&psig=AOvVaw3LkfAx9LQbTekBRdfCoczr&ust=1714247841127000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCMiynf_U4IUDFQAAAAAdAAAAABAr",
        categorie_id: 5,
        origine_id: 6
    },
    {
        chocolat_id: 7,
        nom: "Barre Chocolat Caramel",
        description: "Barre de chocolat au lait avec un cour fondant au caramel.",
        categorie: "Barres de chocolat",
        origine: "Ghana",
        prix: "35000.00",
        image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.femmeactuelle.fr%2Fcuisine%2Ftendance-cuisine%2Fconnaissez-vous-lorigine-de-la-barre-snickers-2105084&psig=AOvVaw2GQDDjqJhwoiwyOiDr77br&ust=1714247688383000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCIDpx7bU4IUDFQAAAAAdAAAAABAZ",
        categorie_id: 6,
        origine_id: 7
    },
    {
        chocolat_id: 20,
        nom: "Tablette Blanc Citron",
        description: "Tablette de chocolat blanc avec une touche de citron acidule.",
        categorie: "Tablettes de chocolat",
        origine: "Ghana",
        prix: "27500.00",
        image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.delscookingtwist.com%2Ffr%2Ftablettes-de-chocolat-blanc-au-citron-et-aux-speculoos%2F&psig=AOvVaw3WENmsQntRxzMd49ZaocCk&ust=1714248138960000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCJjbtY3W4IUDFQAAAAAdAAAAABAT",
        categorie_id: 1,
        origine_id: 7
    }
]