export const chocolates = [
    {
        occurences: 3,
        chocolat_id: 1,
        nom: "Tablette Noir 70%",
        description: "Delicieuse tablette de chocolat noir avec 70% de cacao.",
        categorie: "Tablettes de chocolat",
        origine: "Côte d'Ivoire",
        prix: "38400.00",
        image: "https://zerodechet-tours.fr/233-large_default/tablette-chocolat-noir-amandes.jpg",
        categorie_id: 1,
        origine_id: 1
    },
    {
        occurences: 2,
        chocolat_id: 8,
        nom: "Tablette Noir Intense",
        description: "Tablette de chocolat noir avec 85% de cacao pour une experience intense.",
        categorie: "Tablettes de chocolat",
        origine: "Côte d'Ivoire",
        prix: "39500.00",
        image: "https://fac.img.pmdstatic.net/fit/http.3A.2F.2Fprd2-bone-image.2Es3-website-eu-west-1.2Eamazonaws.2Ecom.2FFAC.2Fvar.2Ffemmeactuelle.2Fstorage.2Fimages.2Fcuisine.2Frecettes-au-chocolat.2Ferreurs-classique-cuisson-du-chocolat-44243.2F14720318-1-fre-FR.2Fces-erreurs-que-l-on-fait-tous-quand-on-cuisine-du-chocolat.2Ejpg/970x485/quality/80/crop-from/center/le-meilleur-des-tablettes-a-patisser.jpeg",
        categorie_id: 1,
        origine_id: 1
    },
    {
        occurences: 1,
        chocolat_id: 14,
        nom: "Tablette Lait Caramel Beurre Sale",
        description: "Tablette de chocolat au lait avec un caramel au beurre sale fondant.",
        categorie: "Tablettes de chocolat",
        origine: "Côte d'Ivoire",
        prix: "43500.00",
        image: "https://www.stephanepasco.com/wp-content/uploads/2020/11/tablette-gourmande-de-stephane-pasco.jpg",
        categorie_id: 1,
        origine_id: 1
    },
    {
        occurences: 5,
        chocolat_id: 9,
        nom: "Praline Noisette",
        description: "Praline fondant aux eclats de noisettes torrefiees.",
        categorie: "Pralinés",
        origine: "Venezuela",
        prix: "44000.00",
        image: "https://www.emotionssucrees.fr/wp-content/uploads/2020/11/tablette-fourree-praline-noisette--scaled.jpg",
        categorie_id: 2,
        origine_id: 2
    },
    {
        chocolat_id: 15,
        nom: "Praline Amande Grillee",
        description: "Praline croquant avec des eclats d amandes grillees.",
        categorie: "Pralinés",
        origine: "Venezuela",
        prix: "47000.00",
        image: "https://chocolats-frigoulette.fr/wp-content/uploads/2023/06/%C2%A9Marianne-Louge-2023-1130-1536x1536.jpg",
        categorie_id: 2,
        origine_id: 2
    },
    {
        chocolat_id: 2,
        nom: "Tablette Lait aux Noisettes",
        description: "Tablette de chocolat au lait avec des eclats de noisettes croquants.",
        categorie: "Tablettes de chocolat",
        origine: "Venezuela",
        prix: "24000.00",
        image: "https://www.secretdecacao.com/wp-content/uploads/2017/09/tablette-lait-noisette-02.jpg",
        categorie_id: 1,
        origine_id: 2
    },
    {
        chocolat_id: 10,
        nom: "Truffe Chocolat Noir",
        description: "Truffe au chocolat noir riche et onctueuse.",
        categorie: "Truffes",
        origine: "Equateur",
        prix: "35500.00",
        image: "https://img.cuisineaz.com/660x660/2020/11/02/i155811-truffes-au-chocolat-copie.jpeg",
        categorie_id: 3,
        origine_id: 3
    },
    {
        chocolat_id: 16,
        nom: "Truffe Chocolat au Lait",
        description: "Truffe au chocolat au lait onctueux et fondant.",
        categorie: "Truffes",
        origine: "Equateur",
        prix: "28900.00",
        image: "https://recettes.de/images/blogs/kilometre-0/truffes-au-chocolat-et-a-l-orange-4237.640x480.jpg",
        categorie_id: 3,
        origine_id: 3
    },
    {
        chocolat_id: 3,
        nom: "Praline Fondant",
        description: "Praline fondant enrobe de chocolat noir.",
        categorie: "Pralinés",
        origine: "Equateur",
        prix: "43200.00",
        image: "https://partagestesrecettes.fr/wp-content/uploads/2020/01/fondant-praline-healthy-1024x1024.png",
        categorie_id: 2,
        origine_id: 3
    },
    {
        chocolat_id: 11,
        nom: "Chocolat Chaud Classique",
        description: "Chocolat chaud traditionnel … base de cacao pur.",
        categorie: "Chocolats chauds",
        origine: "Madagascar",
        prix: "19200.00",
        image: "https://sosoir.lesoir.be/sites/default/files/gallery/buse-doga-ay-gyvgbomx5do-unsplash.jpg",
        categorie_id: 4,
        origine_id: 4
    },
    {
        chocolat_id: 17,
        nom: "Chocolat Chaud Cannelle Vanille",
        description: "Chocolat chaud aromatise … la cannelle et … la vanille pour une touche exotique.",
        categorie: "Chocolats chauds",
        origine: "Madagascar",
        prix: "18000.00",
        image: "https://img.over-blog-kiwi.com/0/93/14/90/20200201/ob_b3566d_chocolat-blanc-chaud-vanille.jpg",
        categorie_id: 4,
        origine_id: 4
    },
    {
        chocolat_id: 4,
        nom: "Truffe Chocolat Blanc",
        description: "Truffe au chocolat blanc avec une touche de vanille.",
        categorie: "Truffes",
        origine: "Madagascar",
        prix: "40000.00",
        image: "https://sf2.viepratique.fr/wp-content/uploads/sites/2/2013/12/shutterstock_69072232.jpg",
        categorie_id: 3,
        origine_id: 4
    },
    {
        chocolat_id: 12,
        nom: "Dragees au Chocolat Blanc",
        description: "Dragees aux amandes enrobees de chocolat blanc.",
        categorie: "Dragées",
        origine: "Pérou",
        prix: "24200.00",
        image: "https://www.badaboum.fr/media/catalog/product/cache/e946e32b6959d67253cf1f4e604a63cc/_/1/_1___1_kilo_de_dragees_blanc_au_chocolat.jpg",
        categorie_id: 5,
        origine_id: 5
    },
    {
        chocolat_id: 18,
        nom: "Dragees aux Noix de Pecan",
        description: "Dragees aux noix de pecan enrobees de chocolat au lait.",
        categorie: "Dragées",
        origine: "Pérou",
        prix: "18500.00",
        image: "https://i0.wp.com/www.fustuq-hail.com/wp-content/uploads/12083-2-jpg.webp?w=1280&ssl=1",
        categorie_id: 5,
        origine_id: 5
    },
    {
        chocolat_id: 5,
        nom: "Chocolat Chaud epice",
        description: "Melange de cacao avec une touche de cannelle et de piment.",
        categorie: "Chocolats chauds",
        origine: "Pérou",
        prix: "28000.00",
        image: "https://img.mesrecettesfaciles.fr/2020-10/chocolat-chaud-aux-epices-d-automne-19786-450.webp",
        categorie_id: 4,
        origine_id: 5
    },
    {
        chocolat_id: 13,
        nom: "Barre Chocolat Noisette",
        description: "Barre de chocolat noir aux eclats de noisettes croustillants.",
        categorie: "Barres de chocolat",
        origine: "Mexique",
        prix: "31000.00",
        image: "https://www.puyricard.fr/6331-large_default/barre-choco-noisettes-caramel.jpg",
        categorie_id: 6,
        origine_id: 6
    },
    {
        chocolat_id: 19,
        nom: "Barre Chocolat au Nougat",
        description: "Barre de chocolat noir avec des morceaux de nougat tendre.",
        categorie: "Barres de chocolat",
        origine: "Mexique",
        prix: "36000.00",
        image: "https://lacabanesurleroc.ca/cdn/shop/files/IMG_4585_720x.jpg?v=1698631256",
        categorie_id: 6,
        origine_id: 6
    },
    {
        chocolat_id: 6,
        nom: "Dragees aux Amandes",
        description: "Dragees aux amandes enrobees de chocolat au lait.",
        categorie: "Dragées",
        origine: "Mexique",
        prix: "32000.00",
        image: "https://cdn1.fleursdedragees.com/4372-pdt_540/1kg-dragees-amande-pas-cher-blanche.webp",
        categorie_id: 5,
        origine_id: 6
    },
    {
        chocolat_id: 7,
        nom: "Barre Chocolat Caramel",
        description: "Barre de chocolat au lait avec un cour fondant au caramel.",
        categorie: "Barres de chocolat",
        origine: "Ghana",
        prix: "35000.00",
        image: "https://www.inuka.com/18706-large_default/mars-barres-chocolat.jpg",
        categorie_id: 6,
        origine_id: 7
    },
    {
        chocolat_id: 20,
        nom: "Tablette Blanc Citron",
        description: "Tablette de chocolat blanc avec une touche de citron acidule.",
        categorie: "Tablettes de chocolat",
        origine: "Ghana",
        prix: "27500.00",
        image: "https://www.delscookingtwist.com/wp-content/uploads/2016/05/White-Chocolate-Bark-with-Lemon_0411-691x1024.jpg",
        categorie_id: 1,
        origine_id: 7
    }
]